### ISSUE TITLE
Erro na inicialização dos pesos nas redes neurais

### ISSUE THREAD

**Issue by matheus-ft** [jbflorindo/MS-MT571#1]
Professor, na célula em que inicializamos aleatoriamente os pesos o senhor faz

```python
epi = (6**1/2)/(L_in+L_out)**1/2
```

Mas dessa forma as raízes quadradas não tomam efeito. Teria de ser assim

```python
epi = (6**(1/2))/(L_in+L_out)**(1/2)
```

Ou, de forma mais limpa

```python
epi = (6 / (L_in+L_out)) ** 0.5
```

Não lembro se na aula o senhor já havia corrigido, ou se entendi errado, perdão, é que parece a intenção tirarmos as raízes.

**Comment by jbflorindo** [comment]
Obrigado, matheus-ft. Tinha corrigido em aula e agora corrigi aqui também!
